# Base Image
FROM ubuntu:18.04

# Metadata
LABEL MAINTAINER Dermot Murphy <dermot.murphy@canembed.com> Name=canembed-arm-ubuntu

# Arguments

# Basic development environment
RUN apt-get update && \
	apt-get install -y zip curl wget && \
	apt-get install -y make && \
	apt-get install -y git  && \
	apt-get install -y subversion  && \
	apt-get install -y doxygen graphviz && \
	apt-get install -y g++  && \
	apt-get install -y python3 python3-pip  && \
	apt-get install -y cpio libncurses5 && \
	apt-get install -y ninja-build && \
	rm -rf /var/lib/apt/lists/*

# CMake (Get the latest release version as Ubuntu has an older version)
# Details at: https://apt.kitware.com/
RUN apt-get install -y apt-transport-https wget
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
RUN apt-get update
RUN rm /usr/share/keyrings/kitware-archive-keyring.gpg
RUN apt-get install -y kitware-archive-keyring
RUN apt-get install -y cmake

# ARM
RUN mkdir /opt/gcc-arm-none-eabi
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2
RUN tar xjfv /tmp/gcc-arm-none-eabi.tar.bz2 -C /opt/gcc-arm-none-eabi --strip-components 1
RUN rm /tmp/gcc-arm-none-eabi.tar.bz2
ENV PATH="/opt/gcc-arm-none-eabi/bin:${PATH}"

# AStyle
RUN mkdir /opt/astyle
RUN mkdir /tmp/astyle
RUN wget -O  /tmp/astyle_3.1_linux.tar.gz https://downloads.sourceforge.net/project/astyle/astyle/astyle%203.1/astyle_3.1_linux.tar.gz
RUN tar -zxf /tmp/astyle_3.1_linux.tar.gz -C /tmp/astyle --strip-components 1
RUN sed -i "s@#include <sys/stat.h>@#include <sys/stat.h>\n        #include <limits.h>@" /tmp/astyle/src/astyle_main.cpp
RUN cd /tmp/astyle && cmake .
RUN cd /tmp/astyle/build/gcc && make
RUN cp /tmp/astyle/build/gcc/bin/astyle /opt/astyle
RUN rm /tmp/astyle_3.1_linux.tar.gz
RUN cd /tmp && rm -R astyle
ENV PATH="/opt/astyle:${PATH}"

# Working directory
WORKDIR /data
VOLUME ["/data"]

# Entry point (which cannot be overriden on the command line but can be appended to)
#ENTRYPOINT

# Default command (which can be overridden on the command line)
CMD ["/bin/bash"]




