# Base Image
FROM ubuntu:18.04

# Metadata
LABEL MAINTAINER Dermot Murphy <dermot.murphy@canembed.com> Name=canembed-arm-ubuntu

# Arguments

# Basic development environment
RUN	apt-get update \
	&& \
	apt-get install -y \
		zip \
		curl \
		wget \
		make \
		git  \
		subversion \
		doxygen \
		graphviz \
		g++ \
		python3 \
		python3-pip \
		cpio \
		libncurses5 \
		ninja-build \
	&& \
	rm -rf /var/lib/apt/lists/*

# CMake (Get the latest release version as Ubuntu has an older version)
# Details at: https://apt.kitware.com/
RUN \
	apt-get install -y \
		apt-transport-https wget \
	&& \
	wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
	&& \
	echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
	&& \
	apt-get update \
	&& \
	rm /usr/share/keyrings/kitware-archive-keyring.gpg \
	&& \
	apt-get install -y \
		kitware-archive-keyring \
		cmake

# ARM
RUN \
	mkdir /opt/gcc-arm-none-eabi \
	&& \
	wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi.tar.bz2 \
	&& \
	tar xjfv /tmp/gcc-arm-none-eabi.tar.bz2 -C /opt/gcc-arm-none-eabi --strip-components 1 \
	&& \
	rm /tmp/gcc-arm-none-eabi.tar.bz2
ENV PATH="/opt/gcc-arm-none-eabi/bin:${PATH}"

# Ruby
RUN \
	apt-get update \
	&& \
	apt-get install -y \
		ruby \
		ruby-dev \
		ruby-bundler \
	&& \
	rm -rf /var/lib/apt/lists/*
  
# AStyle
RUN \
	mkdir /opt/astyle \
	&& \
	mkdir /tmp/astyle \
	&& \
	wget -O  /tmp/astyle_3.1_linux.tar.gz https://downloads.sourceforge.net/project/astyle/astyle/astyle%203.1/astyle_3.1_linux.tar.gz \
	&& \
	tar -zxf /tmp/astyle_3.1_linux.tar.gz -C /tmp/astyle --strip-components 1 \
	&& \
	sed -i "s@#include <sys/stat.h>@#include <sys/stat.h>\n        #include <limits.h>@" /tmp/astyle/src/astyle_main.cpp \
	&& \
	cd /tmp/astyle \
	&& \
	cmake . \
	&& \
	cd /tmp/astyle/build/gcc \
	&& \
	make \
	&& \
	cp /tmp/astyle/build/gcc/bin/astyle /opt/astyle \
	&& \
	rm /tmp/astyle_3.1_linux.tar.gz \
	&& \
	cd /tmp && rm -R astyle
ENV PATH="/opt/astyle:${PATH}"

# Working directory
WORKDIR /data
VOLUME ["/data"]

# Entry point (which cannot be overriden on the command line but can be appended to)
#ENTRYPOINT

# Default command (which can be overridden on the command line)
CMD ["/bin/bash"]




